# Generated by Django 3.0.8 on 2020-08-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(default="Hey there! I'm handeling my accounts", max_length=300)),
                ('contactNo', models.CharField(max_length=14)),
                ('firstN', models.CharField(max_length=20)),
                ('lastN', models.CharField(max_length=20)),
                ('linkedIn', models.URLField(max_length=100)),
                ('github', models.URLField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
