# Generated by Django 3.0.8 on 2020-08-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactNo',
            field=models.CharField(default='1234567890', max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstN',
            field=models.CharField(default='Sita', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(default='http://github.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastN',
            field=models.CharField(default='Ram', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(default='http://linkedin.com', max_length=100),
        ),
    ]
